version: '3.8'

services:
  mercurio:
    build: .
    container_name: mercurio
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./vault:/app/vault
      - ./biblioteca:/app/biblioteca
    networks:
      - mercurio_default
      - olimpo-net

networks:
  mercurio_default:
  olimpo-net:
    external: true
